<a href="https://colab.research.google.com/github/Sg0107/tip-calculcator-start/blob/main/Pytorch3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

#finding gradient
x = torch.rand(3, requires_grad = True)
print(x)
y = x+2
print(y)
z=y*y*2
print(z)
# v=torch.ones(3)
z=z.mean()
z.backward()
print(x.grad)

tensor([0.6335, 0.1971, 0.4353], requires_grad=True)
tensor([2.6335, 2.1971, 2.4353], grad_fn=<AddBackward0>)
tensor([13.8703,  9.6543, 11.8612], grad_fn=<MulBackward0>)
tensor([10.5339,  8.7883,  9.7411])


In [13]:
import torch

# Create a tensor with random values and enable gradient tracking
x = torch.rand(3, requires_grad=True)
print("x:", x)

# Perform a tensor operation
y = x + 2
print("y:", y)

# Perform additional tensor operations
z = y * y * 2
print("z:", z)

# Calculate the mean of tensor z
z_mean = z.mean()
print("z_mean:", z_mean)

# Perform backpropagation to compute gradients
# dz/dx
z_mean.backward() 

# Access the gradients of x
grad_x = x.grad
print("Gradient of x:", grad_x)


# Create a tensor with random values and enable gradient tracking
a = x
print("a:", a)

# Perform a tensor operation
b = a + 2
print("b:", b)

# Perform additional tensor operations
c = b * b * 2
print("c:", c)
v=torch.zeros(3)
# Perform backpropagation to compute gradients
c.backward(v)

# Access the gradients of a
grad_a = a.grad
print("Gradient of a:", grad_a)


# ways to prevent this operation to happen
# 1) x.requires_grad_(False)
# 2) x.detach()
# 3) with torch.no_grad():


x: tensor([0.9540, 0.1998, 0.8002], requires_grad=True)
y: tensor([2.9540, 2.1998, 2.8002], grad_fn=<AddBackward0>)
z: tensor([17.4518,  9.6779, 15.6823], grad_fn=<MulBackward0>)
z_mean: tensor(14.2707, grad_fn=<MeanBackward0>)
Gradient of x: tensor([3.9386, 2.9330, 3.7336])
a: tensor([0.9540, 0.1998, 0.8002], requires_grad=True)
b: tensor([2.9540, 2.1998, 2.8002], grad_fn=<AddBackward0>)
c: tensor([17.4518,  9.6779, 15.6823], grad_fn=<MulBackward0>)
Gradient of a: tensor([3.9386, 2.9330, 3.7336])


In [22]:
import torch

weights = torch.ones(4, requires_grad=True)

for epoch in range (3):
  out = (weights*3).sum()

  out.backward()

  print(weights.grad)


weight = torch.ones(4, requires_grad=True)

for epoch in range (3):
  outs = (weight*3).sum()

  outs.backward()

  print(weight.grad)
  weight.grad.zero_()




tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
