<a href="https://colab.research.google.com/github/Sg0107/tip-calculcator-start/blob/main/Pytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch as th

# how to create a empty tensor
x = th.empty(2, 3, 8)
print(x)

In [ ]:
import torch as th

# tensor with zeros values
x = th.zeros(2,3)
print(x)

In [ ]:
import torch as th

# tensor with ones values
x = th.ones(2,3)
print(x)

In [21]:
import torch as th

# To Check Data type 
x = th.rand(2,3)
print(x.dtype)
# printed data type is default 

# To Change Data type 
x = th.rand(2,3,dtype=th.float64)
print(x.dtype)

# To find size of tensor
x = th.ones(2,3)
print(x.size())

torch.float32
torch.float64
torch.Size([2, 3])


In [22]:
import torch as th

# Manually entering data
x = th.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [27]:
import torch as th

# Basic Operations on tensors
x = th.rand(2,3)
y = th.rand(2,3)
print(x)
print(y)
z = x+y
print(z)
a = th.add(x,y)
print(a)
y.add_(x)
print(y)

tensor([[0.3259, 0.3992, 0.7775],
        [0.8256, 0.3004, 0.6473]])
tensor([[0.6914, 0.1561, 0.0262],
        [0.8054, 0.3648, 0.1017]])
tensor([[1.0173, 0.5554, 0.8037],
        [1.6310, 0.6652, 0.7491]])
tensor([[1.0173, 0.5554, 0.8037],
        [1.6310, 0.6652, 0.7491]])
tensor([[1.0173, 0.5554, 0.8037],
        [1.6310, 0.6652, 0.7491]])


In [32]:
import torch as th

# Slicing of arrays
x = th.rand(5,3)
print(x)
print(x[:2,1:])

# Resizing of arrays
x1 = th.rand(6,4)
print(x1)
y = x1.view(8,3)
print(y)

tensor([[0.7074, 0.8045, 0.7126],
        [0.7652, 0.8395, 0.5527],
        [0.0120, 0.3350, 0.1879],
        [0.1043, 0.5347, 0.3281],
        [0.6119, 0.0503, 0.8904]])
tensor([[0.8045, 0.7126],
        [0.8395, 0.5527]])
tensor([[0.0627, 0.7673, 0.3015, 0.3048],
        [0.0544, 0.3049, 0.4930, 0.5666],
        [0.3451, 0.7897, 0.4782, 0.7822],
        [0.5691, 0.9212, 0.2465, 0.0348],
        [0.8355, 0.6949, 0.6265, 0.4790],
        [0.3951, 0.1329, 0.1712, 0.7870]])
tensor([[0.0627, 0.7673, 0.3015],
        [0.3048, 0.0544, 0.3049],
        [0.4930, 0.5666, 0.3451],
        [0.7897, 0.4782, 0.7822],
        [0.5691, 0.9212, 0.2465],
        [0.0348, 0.8355, 0.6949],
        [0.6265, 0.4790, 0.3951],
        [0.1329, 0.1712, 0.7870]])


In [39]:
import torch as th

# Conversion of numpy to tensor
a=th.ones(5,3)
print(a)
b = a.numpy()
print(b)
print(type(b))

# carefull thing
a.add_(1)
print(a)
print(b)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
